### ISSUE TITLE
Deal with db secrets

### ISSUE THREAD

**Issue by joelbyler** [daveshah/gatherto#19]
Need a way to keep database connections outside of repo and still make it easy to dev.  May be as easy as making a really good explanation in the README for this

**Comment by daveshah** [comment]
It might be kind of nice to have a simple mix task that would generate a secrets file.
something like ```mix gen.secrets``` would be helpful.
I could see this being helpful because it wouldn't just apply to DB connections but also to tokens that we need for Strava, Google, Facebook, etc. that won't be checked into source control.
Would be cool if the mix task would prompt you for what it needed to create the file too, like PG info, Strava tokens, and any additional config info we might need. It would also be nice if it warned you if you were about to overwrite an existing file.

**Comment by mbramson** [comment]
So with the change to fetching database credentials from environment variables, I would think this should be closed as it is no longer necessary.

**Comment by daveshah** [comment]
Yep - closing this for now. I think we can re-open if it becomes a serious problem or if anyone strongly disagrees (in which case, please re-open it if it is a problem).
